export const SIGN_UP_LOADING="auth/signup/loading"
export const SIGN_UP_SUCCESS="auth/signup/success"
export const SIGN_UP_ERROR="auth/signup/error"
export const SIGN_IN_LOADING="auth/signin/loading"
export const SIGN_IN_SUCCESS="auth/signin/success"
export const SIGN_IN_ERROR="auth/signin/error"
export const SIGN_OUT_LOADING="auth/signout/loading"
export const SIGN_OUT_SUCCESS="auth/signout/success"
export const SIGN_OUT_ERROR="auth/signout/error"
export const EMAIL_VERIFY_LOADING="auth/email/loading"
export const EMAIL_VERIFY_SUCCESS="auth/email/success"
export const EMAIL_VERIFY_ERROR="auth/email/error"
export const GET_USER_DETAILS_LOADING="auth/details/loading"
export const GET_USER_DETAILS_SUCCESS="auth/details/success"
export const GET_USER_DETAILS_FAILURE="auth/details/failure"

